In [1]:
import numpy as np

from typing import List

In [20]:
def star_vars(star_centres:np.ndarray, delta_h:float=0.1) -> np.ndarray:
    '''
    Description:
    ------------
    This function generates ``star_points`` based on [1]_ for each
    sample set (i.e., each row consisting of ``star_centres``).
    ``star_centres`` are the points along which in each direction
    the `star_points` are generated. The resolution of sampling is
    :math:`\Delta h` (``delta_h``). This appraoch is a structured
    sampling straregy; read more in [2]_ and [3]_.
    
    
    Arguments:
    ----------
    :param centres: the 2d array (n, m) containing sample sets
                    ``n`` is the number of sample sets and
                    ``m`` is the number of parameters/factors/
                    variables
    :type centres: np.ndarray
    :param delta_h: sampling resolution, defaults to 0.1
    :type delta_h: float
    
    
    Returns:
    --------
    :return star_points: np.array of star points, each element of this 4d
                         array is a 3d np.array with each 2d array containing
                         star points along each parameter/factor/variable.
    :rtype star_points: np.ndarray
    
    
    References:
    -----------
    .. [1] Razavi, S., Sheikholeslami, R., Gupta, H. V., &
           Haghnegahdar, A. (2019). VARS-TOOL: A toolbox for
           comprehensive, efficient, and robust sensitivity 
           and uncertainty analysis. Environmental modelling
           & software, 112, 95-107.
           doi: 10.1016/j.envsoft.2018.10.005
    .. [2] Razavi, S., & Gupta, H. V. (2016). A new framework
           for comprehensive, robust, and efficient global sensitivity
           analysis: 1. Theory. Water Resources Research, 52(1), 423-439.
           doi: 10.1002/2015WR017558
    .. [3] Razavi, S., & Gupta, H. V. (2016). A new framework
           for comprehensive, robust, and efficient global sensitivity
           analysis: 2. Application. Water Resources Research, 52(1),
           423-439. doi: 10.1002/2015WR017559
    
    
    Contributors:
    -------------
    Razavi, Saman, (2016): algorithm, code in MATLAB (c)
    Gupta, Hoshin, (2016): algorithm, code in MATLAB (c)
    Keshavarz, Kasra, (2021): code in Python 3
    '''

    if star_centres.ndim == 1:
        # star_points
        return _star_sampler(star_centres.reshape(1, star_centers.size), delta_h)
    
    elif star_centres.ndim == 2:
        # star_points
        return _star_sampler(star_centres, delta_h)
    
    else:
        # cannot operate on more than 2 dimensional arrays at the moment
        raise ValueError('dimension mismatch: "star_centres" must be a 1- or 2-dimensional array')


def _star_sampler(centres, resolution):
    '''
    
    '''
    # initialize a 4d array 
    star_points = np.zeros((centres.shape[0], \
                            centres.shape[1], \
                            int(1/resolution), \
                            centres.shape[1]))
    
    # fill the array gradually with a for loop
    # there is no other way IMO!
    for i in range(star_points.shape[0]):
        for j in range(star_points.shape[1]):
            star_points[i,j, ...] = np.broadcast_to(centres[i, :], (int(1/resolution), star_points.shape[1])).reshape(int(1/resolution), \
                                                    star_points.shape[1])
            star_points[i, j, ..., j] = _range_vector(centres[i,j], step=resolution)

    return star_points


def _range_vector(num, start=0, end=1, step=0.1):
    '''
    Produces the ranges between 0 and 1 with
    incremental steps while including 0<``num``<1.
    '''

    return np.sort(np.concatenate([-np.arange(-num, start, step)[1:], np.arange(num, end, step)]))

In [21]:
a = np.random.rand(20,5)
a

array([[0.16905063, 0.93259538, 0.91082723, 0.90533541, 0.008527  ],
       [0.08879256, 0.91535613, 0.60371834, 0.33959878, 0.74847387],
       [0.3646195 , 0.008047  , 0.1114922 , 0.61238496, 0.04220749],
       [0.18947409, 0.92137535, 0.19252028, 0.89781543, 0.3043993 ],
       [0.31569873, 0.76239757, 0.65947596, 0.12660649, 0.48035367],
       [0.21746691, 0.27361196, 0.48725712, 0.37287558, 0.58777903],
       [0.76016125, 0.96785637, 0.57017219, 0.4452969 , 0.87547747],
       [0.45026877, 0.26028053, 0.86346143, 0.06613639, 0.44654586],
       [0.80836621, 0.55292408, 0.60906603, 0.08303495, 0.95107167],
       [0.16170643, 0.89635796, 0.15370988, 0.28015183, 0.98772656],
       [0.59704898, 0.88300025, 0.21776289, 0.76878714, 0.64403386],
       [0.76000611, 0.3154646 , 0.48430839, 0.74928813, 0.03700099],
       [0.33841967, 0.85726701, 0.22185116, 0.32399832, 0.32877212],
       [0.34961178, 0.19814846, 0.41161534, 0.44961166, 0.64426586],
       [0.47290348, 0.02560143, 0.

In [22]:
sample = a[0,:]

In [25]:
print(map(_range_vector, sample))

In [24]:
for i in sample:
    print(_range_vector(i))

[0.06905063 0.16905063 0.26905063 0.36905063 0.46905063 0.56905063
 0.66905063 0.76905063 0.86905063 0.96905063]
[0.03259538 0.13259538 0.23259538 0.33259538 0.43259538 0.53259538
 0.63259538 0.73259538 0.83259538 0.93259538]
[0.01082723 0.11082723 0.21082723 0.31082723 0.41082723 0.51082723
 0.61082723 0.71082723 0.81082723 0.91082723]
[0.00533541 0.10533541 0.20533541 0.30533541 0.40533541 0.50533541
 0.60533541 0.70533541 0.80533541 0.90533541]
[0.008527 0.108527 0.208527 0.308527 0.408527 0.508527 0.608527 0.708527
 0.808527 0.908527]


In [28]:
_range_vector(0.2, step=0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [27]:
np.arange(0, 0.8, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])